# nginx proxy address - http://172.17.0.1:8181

name: tautulli
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    pull_policy: always
    container_name: tautulli-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    logging: *default-logging
    networks:
      - tautulli
    ports:
      - "172.17.0.1:8181:8181"
    environment:
      TZ: ${TZ:-America/New_York}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
    volumes:
      - ./volumes/config/tautulli:/config
      - ./volumes/data/tautulli:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8181"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  tautulli:
    name: tautulli
    external: false
